name: cogent3org
channels:
  - conda-forge
  - plotly
dependencies:
  - python=3.7
  - matplotlib
  - pandoc
  - plotly
  - plotly-orca
  - pip
  - pip:
    - numpydoc
    - psutil
    - ipython
    - ipykernel
    - ipywidgets
    - sphinx>=1.6
    - nbsphinx
    - nbformat
    - nbconvert!=5.4
    - sphinxcontrib-bibtex
    - sphinx-gallery
    - ../
