on:
  push:
    branches:
    - 'master'

jobs:
    source:
        name: Build cogent3 org website and docs
        runs-on: 'macos-latest'
        steps:
          - uses: actions/checkout@v2
            with:
               repository: cogent3/cogent3
               path: cogent3-source
               ref: develop

          - uses: actions/checkout@v2
            with:
               path: cogent3-org

          - name: Debug step
            shell: bash -l {0}
            working-directory: cogent3-source/doc/
            run: |
              pwd
              echo "parents parent ../.."
              ls ../..
              echo "should be dest"
              ls ../../cogent3-org/docs
              die

          - uses: goanpeca/setup-miniconda@v1
            with:
               activate-environment: cogent3
               environment-file: cogent3-source/doc/rtd-environment.yml
               python-version: 3.8

          - shell: bash -l {0}
            run: |
              conda info --envs
              conda activate cogent3
              conda info
              conda list

          - name: Build source docs
            shell: bash -l {0}
            working-directory: cogent3-source/doc/
            run: |
              pwd
              conda activate cogent3
              make github
              mv ../docs ../../cogent3-org/docs/dev

          - shell: bash -l {0}
            run: |
              conda activate cogent3
              conda info
              conda list

          - name: Build org docs
            shell: bash -l {0}
            working-directory: cogent3-org/doc/
            run: |
              conda activate cogent3
              make github

          - name: Deploy docs
            uses: peaceiris/actions-gh-pages@v3
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./docs
