on:
  push:
    branches:
    - develop

jobs:
  example-3:
    name: Doc Build
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v2
        with:
           path: c3org

      - uses: actions/checkout@v2
        with:
           repository: cogent3/cogent3
           path: c3src
           ref: develop

      - name: Move source docs into place
      - shell: bash -l {0}
        run: |
          mv c3src/doc c3org/doc/doc

